server:
  profiles:
    active: dev
---
server:
  port: 8001

spring:
  profiles: dev #测试环境
  application:
    name: microservicecloud-dept #对外暴露的微服务名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: z123456
    dbcp2: #启用dbcp2配置
      min-idle: 5 #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,
      initial-size: 5 #初始化连接数量
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.molv.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    instance:
      instance-id: microservicecloud-dept8001 #自定义服务名称信息
      #prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: molv-microservicecloud
  company.name: www.molv.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8101

spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-dept #对外暴露的微服务名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: z123456
    dbcp2: #启用dbcp2配置
      min-idle: 5 #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,
      initial-size: 5 #初始化连接数量
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.molv.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    instance:
      instance-id: microservicecloud-dept8001 #自定义服务名称信息
      #prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: molv-microservicecloud
  company.name: www.molv.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
#保存为UTF-8格式